/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ComputeFXEffect
@P   - ComputeEffectShader.ThreadNumbers: X:64 Y:1 Z:1
@P EffectNodeBase.EffectNodeBaseShader: mixin ComputeFXGraph [{Root = mixin ComputeOrder [{Computes = [Shader_418374866]}]}]
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDispatch [Size: 32]
@C    ThreadGroupCountGlobal_id10 => ComputeShaderBase.ThreadGroupCountGlobal
@C    input_274178031_id14 => input_274178031
@C    input_4179708374_id15 => input_4179708374
@C    input_3474858554_id16 => input_3474858554
***************************
******  Resources    ******
***************************
@R    DynamicBufferInput_58384011_id12 => DynamicBufferInput_58384011 [Stage: Compute, Slot: (0-0)]
@R    DynamicBufferInput_2568742062_id13 => DynamicBufferInput_2568742062 [Stage: Compute, Slot: (1-1)]
@R    PerDispatch => PerDispatch [Stage: Compute, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    ComputeShaderBase => 8f045851eaa4513eb38a704d53889e6d
@S    ComputeFXGraph => dca3deb94a1ea6d5babe444153dee98b
@S    ComputeVoid => b62583a94b8503c79e9107f4b5bc9392
@S    ComputeOrder => 1d9b1cd3f5e3ad3f3f10e4fc88326cc7
@S    Shader_418374866 => 29a8c22706d1455314565e7f2d123068
***************************
*****     Stages      *****
***************************
@G    Compute => 603851c62eb79819326612ab431e9fa2
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDispatch
// {
//
//   int3 ThreadGroupCountGlobal_id10;  // Offset:    0 Size:    12 [unused]
//   int input_274178031_id14;          // Offset:   12 Size:     4
//   float input_4179708374_id15;       // Offset:   16 Size:     4 [unused]
//   float3 input_3474858554_id16;      // Offset:   20 Size:    12 [unused]
//
// }
//
// Resource bind info for DynamicBufferInput_58384011_id12
// {
//
//   struct PSystem
//   {
//       
//       float Age;                     // Offset:    0
//       float LifeTime;                // Offset:    4
//       int Id;                        // Offset:    8
//       float3 PPosition;              // Offset:   12
//       float3 Velocity;               // Offset:   24
//       float Size;                    // Offset:   36
//       float Mass;                    // Offset:   40
//       float4 PColor;                 // Offset:   44
//       int Cycle;                     // Offset:   60
//       float3 Target;                 // Offset:   64
//       float3 Size3;                  // Offset:   76
//       float3 AxisX;                  // Offset:   88
//       float3 AxisY;                  // Offset:  100
//       float3 AxisZ;                  // Offset:  112
//
//   } $Element;                        // Offset:    0 Size:   124
//
// }
//
// Resource bind info for DynamicBufferInput_2568742062_id13
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// DynamicBufferInput_58384011_id12        UAV  struct         r/w             u0      1 
// DynamicBufferInput_2568742062_id13        UAV  struct      append             u1      1 
// PerDispatch                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_uav_structured u0, 124
dcl_uav_structured u1, 4
dcl_input vThreadID.x
dcl_temps 1
dcl_thread_group 64, 1, 1
//
// Initial variable locations:
//   vThreadGroupID.x <- __input__.GroupId_id0.x; vThreadGroupID.y <- __input__.GroupId_id0.y; vThreadGroupID.z <- __input__.GroupId_id0.z; 
//   vThreadID.x <- __input__.DispatchThreadId_id1.x; vThreadID.y <- __input__.DispatchThreadId_id1.y; vThreadID.z <- __input__.DispatchThreadId_id1.z
//
#line 50 "C:\Projects\MOTF\MOTF_VVVV_6.3\vvvv_gamma_6.3\log\shader_ComputeFXEffect_85e376efe95538701fa206c8ded8a0a6.hlsl"
ult r0.x, vThreadID.x, cb0[0].w
if_nz r0.x

#line 59
  imm_atomic_alloc r0.x, u1
  store_structured u1.x, r0.x, l(0), vThreadID.x

#line 65
  store_structured u0.x, vThreadID.x, l(0), l(-1.000000)
endif 

#line 91
ret 
// Approximately 7 instruction slots used
***************************
*************************/
struct CS_STREAMS 
{
    uint3 GroupId_id0;
    uint3 DispatchThreadId_id1;
    int ThreadCountX_id7;
    int ThreadCountY_id8;
    int ThreadCountZ_id9;
    uint ThreadCountPerGroup_id5;
    uint3 ThreadGroupCount_id4;
    uint ThreadGroupIndex_id6;
};
struct CS_INPUT 
{
    uint3 GroupId_id0 : SV_GroupID;
    uint3 DispatchThreadId_id1 : SV_DispatchThreadID;
};
struct PSystem 
{
    float Age;
    float LifeTime;
    int Id;
    float3 PPosition;
    float3 Velocity;
    float Size;
    float Mass;
    float4 PColor;
    int Cycle;
    float3 Target;
    float3 Size3;
    float3 AxisX;
    float3 AxisY;
    float3 AxisZ;
};
cbuffer PerDispatch 
{
    int3 ThreadGroupCountGlobal_id10;
    int input_274178031_id14;
    float input_4179708374_id15;
    float3 input_3474858554_id16;
};
RWStructuredBuffer<PSystem> DynamicBufferInput_58384011_id12;
AppendStructuredBuffer<int> DynamicBufferInput_2568742062_id13;
void Compute_id4(inout CS_STREAMS streams)
{
    bool Assign_1729966471 = streams.DispatchThreadId_id1.x >= input_274178031_id14;
    if (Assign_1729966471)
    {
        return;
    }
    int IndexX_2446700840 = streams.DispatchThreadId_id1.x;
    PSystem getBuffer_2805507595 = DynamicBufferInput_58384011_id12[IndexX_2446700840];
    float age_2090133185 = getBuffer_2805507595.Age;
    float deltatime_1022169785 = 0;
    deltatime_1022169785 = input_4179708374_id15;
    int3 index_1816214622 = int3(0, 0, 0);
    index_1816214622 = streams.DispatchThreadId_id1;
    float3 resourcescale_4057661955 = float3(0, 0, 0);
    resourcescale_4057661955 = input_3474858554_id16;
    DynamicBufferInput_2568742062_id13.Append(streams.DispatchThreadId_id1.x);
    int IndexX_2_2446700840 = streams.DispatchThreadId_id1.x;
    PSystem getBuffer_2_2805507595 = DynamicBufferInput_58384011_id12[IndexX_2_2446700840];
    float age_2_2090133185 = getBuffer_2_2805507595.Age;
    age_2_2090133185 = -1;
    getBuffer_2805507595.Age = age_2_2090133185;
    DynamicBufferInput_58384011_id12[IndexX_2446700840] = getBuffer_2805507595;
}
void Compute_id3(inout CS_STREAMS streams)
{

    {
        Compute_id4(streams);
    }
}
void Compute_id2(inout CS_STREAMS streams)
{
    Compute_id3(streams);
}
[numthreads(64, 1, 1)]
void CSMain(CS_INPUT __input__)
{
    CS_STREAMS streams = (CS_STREAMS)0;
    streams.GroupId_id0 = __input__.GroupId_id0;
    streams.DispatchThreadId_id1 = __input__.DispatchThreadId_id1;
    streams.ThreadCountX_id7 = 64;
    streams.ThreadCountY_id8 = 1;
    streams.ThreadCountZ_id9 = 1;
    streams.ThreadCountPerGroup_id5 = 64 * 1 * 1;
    streams.ThreadGroupCount_id4 = ThreadGroupCountGlobal_id10;
    streams.ThreadGroupIndex_id6 = (streams.GroupId_id0.z * streams.ThreadGroupCount_id4.y + streams.GroupId_id0.y) * streams.ThreadGroupCount_id4.x + streams.GroupId_id0.x;
    Compute_id2(streams);
}
