/**************************
***** Compiler Parameters *****
***************************
@P EffectName: Shader_1042016781
***************************
****  ConstantBuffers  ****
***************************
cbuffer Inputs [Size: 80]
@C    input_2345886612_id45 => input_2345886612
@C    input_2340563897_id46 => input_2340563897
@C    input_839765076_id47 => input_839765076
@C    input_2391782587_id48 => input_2391782587
@C    input_157705887_id49 => input_157705887
@C    input_507318587_id50 => input_507318587
@C    input_2135914162_id51 => input_2135914162
@C    input_942655201_id52 => input_942655201
@C    input_1965808618_id53 => input_1965808618
@C    input_1408606897_id54 => input_1408606897
cbuffer PerDraw [Size: 416]
@C    World_id33 => Transformation.World
@C    WorldInverse_id34 => Transformation.WorldInverse
@C    WorldInverseTranspose_id35 => Transformation.WorldInverseTranspose
@C    WorldView_id36 => Transformation.WorldView
@C    WorldViewInverse_id37 => Transformation.WorldViewInverse
@C    WorldViewProjection_id38 => Transformation.WorldViewProjection
@C    WorldScale_id39 => Transformation.WorldScale
@C    EyeMS_id40 => Transformation.EyeMS
***************************
******  Resources    ******
***************************
@R    Inputs => Inputs [Stage: Vertex, Slot: (0-0)]
@R    PerDraw => PerDraw [Stage: Vertex, Slot: (1-1)]
@R    Inputs => Inputs [Stage: Pixel, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    Shader_1042016781 => 4754d247d64508e56a8b1ec64304847a
@S    ShaderBase => 4ecbcd2528b64a79eebe81a863892d8c
@S    ShaderBaseStream => b705b699a7385d39c7de52a8d13f3978
@S    PositionStream4 => 992b49e1b4dd13d8ef84a05830d70229
@S    FuseCoreTransform => b43eea1eed94d0f94cf8f317663a8207
@S    FuseCoreMath => b5527ab1f8082f68a6dcc7c3959ee99a
@S    FuseCommonTypes => 6c2f0b095ce5f1d9e2781b56961676cd
@S    Transformation => 7c995c14d4da978d7dca233f15f1e7c0
@S    FuseCoreColor => b38a45e225b62858620e5f0c43643897
@S    FuseCoreMathMap => 94c96291dfc2dcadc0ac8216795ab179
@S    FuseCommonNoise => f3e94fe4a03a0b02051750e5b6a831ca
@S    FuseCommonNoiseSine => d8c809697d88a8d534414c8b788f34bd
@S    FuseCoreMathHash => 9e8ec916d08625592014904eea5076c5
@S    FuseCommonNoiseValueNoise => 598ea3c9dd7c5fed506e079ef91b1d81
@S    FuseCommonNoiseGradientNoise => 275a1c68a04d0e8c934e4792e8de1a02
@S    FuseCommonNoiseSimplex => cff83c6dcba0e92106f65f2c730e3e35
@S    FuseCommonNoiseRandom => c9e5885d1263580889df6cfb5c437ec3
@S    FuseCommonNoiseWorley => d0830642cb2e69b2f30256019c06d7a7
***************************
*****     Stages      *****
***************************
@G    Vertex => fc7addcf155efe2b443d88130f026eb5
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer Inputs
// {
//
//   float input_2345886612_id45;       // Offset:    0 Size:     4
//   float input_2340563897_id46;       // Offset:    4 Size:     4 [unused]
//   float3 input_839765076_id47;       // Offset:   16 Size:    12 [unused]
//   float3 input_2391782587_id48;      // Offset:   32 Size:    12 [unused]
//   float input_157705887_id49;        // Offset:   44 Size:     4 [unused]
//   float input_507318587_id50;        // Offset:   48 Size:     4 [unused]
//   float input_2135914162_id51;       // Offset:   52 Size:     4 [unused]
//   float input_942655201_id52;        // Offset:   56 Size:     4 [unused]
//   float input_1965808618_id53;       // Offset:   60 Size:     4 [unused]
//   float input_1408606897_id54;       // Offset:   64 Size:     4 [unused]
//
// }
//
// cbuffer PerDraw
// {
//
//   float4x4 World_id33;               // Offset:    0 Size:    64 [unused]
//   float4x4 WorldInverse_id34;        // Offset:   64 Size:    64 [unused]
//   float4x4 WorldInverseTranspose_id35;// Offset:  128 Size:    64 [unused]
//   float4x4 WorldView_id36;           // Offset:  192 Size:    64 [unused]
//   float4x4 WorldViewInverse_id37;    // Offset:  256 Size:    64 [unused]
//   float4x4 WorldViewProjection_id38; // Offset:  320 Size:    64
//   float3 WorldScale_id39;            // Offset:  384 Size:    12 [unused]
//   float4 EyeMS_id40;                 // Offset:  400 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// Inputs                            cbuffer      NA          NA            cb0      1 
// PerDraw                           cbuffer      NA          NA            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyzw        0     NONE   float   xyzw
// PPOSITION                0   xyz         1     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float   xyzw
// POSITION                 0   xyzw        1     NONE   float   xyzw
// PPOSITION                0   xyz         2     NONE   float   xyz 
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[1], immediateIndexed
dcl_constantbuffer CB1[24], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xyz
dcl_output_siv o0.xyzw, position
dcl_output o1.xyzw
dcl_output o2.xyz
dcl_temps 2
//
// Initial variable locations:
//   v0.x <- __input__.Position_id14.x; v0.y <- __input__.Position_id14.y; v0.z <- __input__.Position_id14.z; v0.w <- __input__.Position_id14.w; 
//   v1.x <- __input__.PPosition_id55.x; v1.y <- __input__.PPosition_id55.y; v1.z <- __input__.PPosition_id55.z; 
//   o2.x <- <VSMain return value>.PPosition_id55.x; o2.y <- <VSMain return value>.PPosition_id55.y; o2.z <- <VSMain return value>.PPosition_id55.z; 
//   o1.x <- <VSMain return value>.Position_id14.x; o1.y <- <VSMain return value>.Position_id14.y; o1.z <- <VSMain return value>.Position_id14.z; o1.w <- <VSMain return value>.Position_id14.w; 
//   o0.x <- <VSMain return value>.ShadingPosition_id0.x; o0.y <- <VSMain return value>.ShadingPosition_id0.y; o0.z <- <VSMain return value>.ShadingPosition_id0.z; o0.w <- <VSMain return value>.ShadingPosition_id0.w
//
#line 154 "C:\Projects\MOTF\MOTF_VVVV_6.3\vvvv_gamma_6.3\log\shader_Shader_1042016781_228041a7634791cb2083a2005e7c4d58.hlsl"
mul r0.x, cb0[0].x, l(6.283185)  // r0.x <- a

#line 157
sincos r0.x, r1.x, r0.x  // r1.x <- c; r0.x <- s

#line 160
mul r0.yz, r1.xxxx, v0.xxzx

#line 159
mad r1.x, r0.x, v0.z, r0.y  // r1.x <- p.x

#line 160
mad r1.z, -r0.x, v0.x, r0.z  // r1.z <- p.z

#line 191
mov r1.y, v0.y
mov r1.w, l(1.000000)
dp4 o0.x, r1.xyzw, cb1[20].xyzw
dp4 o0.y, r1.xyzw, cb1[21].xyzw
dp4 o0.z, r1.xyzw, cb1[22].xyzw
dp4 o0.w, r1.xyzw, cb1[23].xyzw

#line 197
mov o1.xyzw, v0.xyzw
mov o2.xyz, v1.xyzx
ret 
// Approximately 14 instruction slots used
@G    Pixel => ebcea9fcb029cac9973f97690bc7bace
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer Inputs
// {
//
//   float input_2345886612_id45;       // Offset:    0 Size:     4 [unused]
//   float input_2340563897_id46;       // Offset:    4 Size:     4
//   float3 input_839765076_id47;       // Offset:   16 Size:    12
//   float3 input_2391782587_id48;      // Offset:   32 Size:    12
//   float input_157705887_id49;        // Offset:   44 Size:     4
//   float input_507318587_id50;        // Offset:   48 Size:     4
//   float input_2135914162_id51;       // Offset:   52 Size:     4
//   float input_942655201_id52;        // Offset:   56 Size:     4
//   float input_1965808618_id53;       // Offset:   60 Size:     4
//   float input_1408606897_id54;       // Offset:   64 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// Inputs                            cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Position              0   xyzw        0      POS   float       
// POSITION                 0   xyzw        1     NONE   float       
// PPOSITION                0   xyz         2     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_Target                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[5], immediateIndexed
dcl_input_ps linear v2.xyz
dcl_output o0.xyzw
dcl_temps 6
//
// Initial variable locations:
//   v0.x <- __input__.ShadingPosition_id0.x; v0.y <- __input__.ShadingPosition_id0.y; v0.z <- __input__.ShadingPosition_id0.z; v0.w <- __input__.ShadingPosition_id0.w; 
//   v1.x <- __input__.Position_id14.x; v1.y <- __input__.Position_id14.y; v1.z <- __input__.Position_id14.z; v1.w <- __input__.Position_id14.w; 
//   v2.x <- __input__.PPosition_id55.x; v2.y <- __input__.PPosition_id55.y; v2.z <- __input__.PPosition_id55.z; 
//   o0.x <- <PSMain return value>.ColorTarget_id2.x; o0.y <- <PSMain return value>.ColorTarget_id2.y; o0.z <- <PSMain return value>.ColorTarget_id2.z; o0.w <- <PSMain return value>.ColorTarget_id2.w
//
#line 134 "C:\Projects\MOTF\MOTF_VVVV_6.3\vvvv_gamma_6.3\log\shader_Shader_1042016781_228041a7634791cb2083a2005e7c4d58.hlsl"
mov r0.w, cb0[0].y  // r0.w <- result_1273172016.w

#line 136
mad r0.xyz, v2.xyzx, cb0[1].xyzx, cb0[2].xyzx  // r0.x <- result_1273172016.x; r0.y <- result_1273172016.y; r0.z <- result_1273172016.z

#line 82
round_ni r1.xyzw, r0.zywx  // r1.x <- i.z; r1.y <- i.y; r1.z <- i.w; r1.w <- i.x

#line 83
frc r0.xyzw, r0.xyzw  // r0.x <- f.x; r0.y <- f.y; r0.z <- f.z; r0.w <- f.w

#line 85
add r2.xyzw, r1.xyzw, l(1.000000, 1.000000, 1.000000, 1.000000)

#line 76
mul r2.xyzw, r2.xyzw, l(0.097300, 0.103000, 0.109900, 0.103100)
frc r2.xyzw, r2.xyzw  // r2.x <- p4.z; r2.y <- p4.y; r2.z <- p4.w; r2.w <- p4.x

#line 77
add r3.xyzw, r2.zxwy, l(19.190001, 19.190001, 19.190001, 19.190001)
dp4 r3.x, r2.wyxz, r3.xyzw
add r2.xyzw, r2.xyzw, r3.xxxx

#line 78
add r3.xyzw, r2.yxxz, r2.wwyx
mul r2.xyzw, r2.xyzw, r3.xyzw
frc r2.xyzw, r2.xyzw  // r2.x <- <hash44_id199 return value>.x; r2.y <- <hash44_id199 return value>.y; r2.z <- <hash44_id199 return value>.z; r2.w <- <hash44_id199 return value>.w

#line 85
mad r2.xyzw, r2.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(-1.000000, -1.000000, -1.000000, -1.000000)
add r3.xyzw, r0.xyzw, l(-1.000000, -1.000000, -1.000000, -1.000000)
dp4 r2.x, r2.xyzw, r3.xyzw
add r3.xyzw, r1.xyzw, l(1.000000, 1.000000, 1.000000, 0.000000)

#line 76
mul r3.xyzw, r3.xyzw, l(0.097300, 0.103000, 0.109900, 0.103100)
frc r3.xyzw, r3.xyzw  // r3.x <- p4.z; r3.y <- p4.y; r3.z <- p4.w; r3.w <- p4.x

#line 77
add r4.xyzw, r3.zxwy, l(19.190001, 19.190001, 19.190001, 19.190001)
dp4 r2.y, r3.wyxz, r4.xyzw
add r3.xyzw, r2.yyyy, r3.xyzw

#line 78
add r4.xyzw, r3.yxxz, r3.wwyx
mul r3.xyzw, r3.xyzw, r4.xyzw
frc r3.xyzw, r3.xyzw  // r3.x <- <hash44_id199 return value>.x; r3.y <- <hash44_id199 return value>.y; r3.z <- <hash44_id199 return value>.z; r3.w <- <hash44_id199 return value>.w

#line 85
mad r3.xyzw, r3.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(-1.000000, -1.000000, -1.000000, -1.000000)
add r4.xyzw, r0.xyzw, l(-0.000000, -1.000000, -1.000000, -1.000000)
dp4 r2.y, r3.xyzw, r4.xyzw
add r2.x, -r2.y, r2.x

#line 84
mul r3.xyzw, r0.xyzw, r0.xyzw
mad r4.xyzw, -r0.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(3.000000, 3.000000, 3.000000, 3.000000)
mul r3.xyzw, r3.xyzw, r4.xyzw  // r3.x <- u.x; r3.y <- u.y; r3.z <- u.z; r3.w <- u.w

#line 85
mad r2.x, r3.x, r2.x, r2.y
add r4.xyzw, r1.xyzw, l(1.000000, 0.000000, 1.000000, 1.000000)

#line 76
mul r4.xyzw, r4.xyzw, l(0.097300, 0.103000, 0.109900, 0.103100)
frc r4.xyzw, r4.xyzw  // r4.x <- p4.z; r4.y <- p4.y; r4.z <- p4.w; r4.w <- p4.x

#line 77
add r5.xyzw, r4.zxwy, l(19.190001, 19.190001, 19.190001, 19.190001)
dp4 r2.y, r4.wyxz, r5.xyzw
add r4.xyzw, r2.yyyy, r4.xyzw

#line 78
add r5.xyzw, r4.yxxz, r4.wwyx
mul r4.xyzw, r4.xyzw, r5.xyzw
frc r4.xyzw, r4.xyzw  // r4.x <- <hash44_id199 return value>.x; r4.y <- <hash44_id199 return value>.y; r4.z <- <hash44_id199 return value>.z; r4.w <- <hash44_id199 return value>.w

#line 85
mad r4.xyzw, r4.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(-1.000000, -1.000000, -1.000000, -1.000000)
add r5.xyzw, r0.xyzw, l(-1.000000, -0.000000, -1.000000, -1.000000)
dp4 r2.y, r4.xyzw, r5.xyzw
add r4.xyzw, r1.xyzw, l(1.000000, 0.000000, 1.000000, 0.000000)

#line 76
mul r4.xyzw, r4.xyzw, l(0.097300, 0.103000, 0.109900, 0.103100)
frc r4.xyzw, r4.xyzw  // r4.x <- p4.z; r4.y <- p4.y; r4.z <- p4.w; r4.w <- p4.x

#line 77
add r5.xyzw, r4.zxwy, l(19.190001, 19.190001, 19.190001, 19.190001)
dp4 r2.z, r4.wyxz, r5.xyzw
add r4.xyzw, r2.zzzz, r4.xyzw

#line 78
add r5.xyzw, r4.yxxz, r4.wwyx
mul r4.xyzw, r4.xyzw, r5.xyzw
frc r4.xyzw, r4.xyzw  // r4.x <- <hash44_id199 return value>.x; r4.y <- <hash44_id199 return value>.y; r4.z <- <hash44_id199 return value>.z; r4.w <- <hash44_id199 return value>.w

#line 85
mad r4.xyzw, r4.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(-1.000000, -1.000000, -1.000000, -1.000000)
add r5.xyzw, r0.xyzw, l(-0.000000, -0.000000, -1.000000, -1.000000)
dp4 r2.z, r4.xyzw, r5.xyzw
add r2.y, -r2.z, r2.y
mad r2.y, r3.x, r2.y, r2.z
add r2.x, -r2.y, r2.x
mad r2.x, r3.y, r2.x, r2.y
add r4.xyzw, r1.xyzw, l(0.000000, 1.000000, 1.000000, 1.000000)

#line 76
mul r4.xyzw, r4.xyzw, l(0.097300, 0.103000, 0.109900, 0.103100)
frc r4.xyzw, r4.xyzw  // r4.x <- p4.z; r4.y <- p4.y; r4.z <- p4.w; r4.w <- p4.x

#line 77
add r5.xyzw, r4.zxwy, l(19.190001, 19.190001, 19.190001, 19.190001)
dp4 r2.y, r4.wyxz, r5.xyzw
add r4.xyzw, r2.yyyy, r4.xyzw

#line 78
add r5.xyzw, r4.yxxz, r4.wwyx
mul r4.xyzw, r4.xyzw, r5.xyzw
frc r4.xyzw, r4.xyzw  // r4.x <- <hash44_id199 return value>.x; r4.y <- <hash44_id199 return value>.y; r4.z <- <hash44_id199 return value>.z; r4.w <- <hash44_id199 return value>.w

#line 85
mad r4.xyzw, r4.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(-1.000000, -1.000000, -1.000000, -1.000000)
add r5.xyzw, r0.xyzw, l(-1.000000, -1.000000, -0.000000, -1.000000)
dp4 r2.y, r4.xyzw, r5.xyzw
add r4.xyzw, r1.xyzw, l(0.000000, 1.000000, 1.000000, 0.000000)

#line 76
mul r4.xyzw, r4.xyzw, l(0.097300, 0.103000, 0.109900, 0.103100)
frc r4.xyzw, r4.xyzw  // r4.x <- p4.z; r4.y <- p4.y; r4.z <- p4.w; r4.w <- p4.x

#line 77
add r5.xyzw, r4.zxwy, l(19.190001, 19.190001, 19.190001, 19.190001)
dp4 r2.z, r4.wyxz, r5.xyzw
add r4.xyzw, r2.zzzz, r4.xyzw

#line 78
add r5.xyzw, r4.yxxz, r4.wwyx
mul r4.xyzw, r4.xyzw, r5.xyzw
frc r4.xyzw, r4.xyzw  // r4.x <- <hash44_id199 return value>.x; r4.y <- <hash44_id199 return value>.y; r4.z <- <hash44_id199 return value>.z; r4.w <- <hash44_id199 return value>.w

#line 85
mad r4.xyzw, r4.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(-1.000000, -1.000000, -1.000000, -1.000000)
add r5.xyzw, r0.xyzw, l(-0.000000, -1.000000, -0.000000, -1.000000)
dp4 r2.z, r4.xyzw, r5.xyzw
add r2.y, -r2.z, r2.y
mad r2.y, r3.x, r2.y, r2.z
add r4.xyzw, r1.xyzw, l(0.000000, 0.000000, 1.000000, 1.000000)

#line 76
mul r4.xyzw, r4.xyzw, l(0.097300, 0.103000, 0.109900, 0.103100)
frc r4.xyzw, r4.xyzw  // r4.x <- p4.z; r4.y <- p4.y; r4.z <- p4.w; r4.w <- p4.x

#line 77
add r5.xyzw, r4.zxwy, l(19.190001, 19.190001, 19.190001, 19.190001)
dp4 r2.z, r4.wyxz, r5.xyzw
add r4.xyzw, r2.zzzz, r4.xyzw

#line 78
add r5.xyzw, r4.yxxz, r4.wwyx
mul r4.xyzw, r4.xyzw, r5.xyzw
frc r4.xyzw, r4.xyzw  // r4.x <- <hash44_id199 return value>.x; r4.y <- <hash44_id199 return value>.y; r4.z <- <hash44_id199 return value>.z; r4.w <- <hash44_id199 return value>.w

#line 85
mad r4.xyzw, r4.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(-1.000000, -1.000000, -1.000000, -1.000000)
add r5.xyzw, r0.xyzw, l(-1.000000, -0.000000, -0.000000, -1.000000)
dp4 r2.z, r4.xyzw, r5.xyzw
add r4.xyzw, r1.xyzw, l(0.000000, 0.000000, 1.000000, 0.000000)

#line 76
mul r4.xyzw, r4.xyzw, l(0.097300, 0.103000, 0.109900, 0.103100)
frc r4.xyzw, r4.xyzw  // r4.x <- p4.z; r4.y <- p4.y; r4.z <- p4.w; r4.w <- p4.x

#line 77
add r5.xyzw, r4.zxwy, l(19.190001, 19.190001, 19.190001, 19.190001)
dp4 r2.w, r4.wyxz, r5.xyzw
add r4.xyzw, r2.wwww, r4.xyzw

#line 78
add r5.xyzw, r4.yxxz, r4.wwyx
mul r4.xyzw, r4.xyzw, r5.xyzw
frc r4.xyzw, r4.xyzw  // r4.x <- <hash44_id199 return value>.x; r4.y <- <hash44_id199 return value>.y; r4.z <- <hash44_id199 return value>.z; r4.w <- <hash44_id199 return value>.w

#line 85
mad r4.xyzw, r4.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(-1.000000, -1.000000, -1.000000, -1.000000)
add r5.xyzw, r0.xyzw, l(-0.000000, -0.000000, -0.000000, -1.000000)
dp4 r2.w, r4.xyzw, r5.xyzw
add r2.z, -r2.w, r2.z
mad r2.z, r3.x, r2.z, r2.w
add r2.y, -r2.z, r2.y
mad r2.y, r3.y, r2.y, r2.z
add r2.x, -r2.y, r2.x
mad r2.x, r3.z, r2.x, r2.y
add r4.xyzw, r1.xyzw, l(1.000000, 1.000000, 0.000000, 1.000000)

#line 76
mul r4.xyzw, r4.xyzw, l(0.097300, 0.103000, 0.109900, 0.103100)
frc r4.xyzw, r4.xyzw  // r4.x <- p4.z; r4.y <- p4.y; r4.z <- p4.w; r4.w <- p4.x

#line 77
add r5.xyzw, r4.zxwy, l(19.190001, 19.190001, 19.190001, 19.190001)
dp4 r2.y, r4.wyxz, r5.xyzw
add r4.xyzw, r2.yyyy, r4.xyzw

#line 78
add r5.xyzw, r4.yxxz, r4.wwyx
mul r4.xyzw, r4.xyzw, r5.xyzw
frc r4.xyzw, r4.xyzw  // r4.x <- <hash44_id199 return value>.x; r4.y <- <hash44_id199 return value>.y; r4.z <- <hash44_id199 return value>.z; r4.w <- <hash44_id199 return value>.w

#line 85
mad r4.xyzw, r4.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(-1.000000, -1.000000, -1.000000, -1.000000)
add r5.xyzw, r0.xyzw, l(-1.000000, -1.000000, -1.000000, -0.000000)
dp4 r2.y, r4.xyzw, r5.xyzw
add r4.xyzw, r1.xyzw, l(1.000000, 1.000000, 0.000000, 0.000000)

#line 76
mul r4.xyzw, r4.xyzw, l(0.097300, 0.103000, 0.109900, 0.103100)
frc r4.xyzw, r4.xyzw  // r4.x <- p4.z; r4.y <- p4.y; r4.z <- p4.w; r4.w <- p4.x

#line 77
add r5.xyzw, r4.zxwy, l(19.190001, 19.190001, 19.190001, 19.190001)
dp4 r2.z, r4.wyxz, r5.xyzw
add r4.xyzw, r2.zzzz, r4.xyzw

#line 78
add r5.xyzw, r4.yxxz, r4.wwyx
mul r4.xyzw, r4.xyzw, r5.xyzw
frc r4.xyzw, r4.xyzw  // r4.x <- <hash44_id199 return value>.x; r4.y <- <hash44_id199 return value>.y; r4.z <- <hash44_id199 return value>.z; r4.w <- <hash44_id199 return value>.w

#line 85
mad r4.xyzw, r4.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(-1.000000, -1.000000, -1.000000, -1.000000)
add r5.xyzw, r0.xyzw, l(-0.000000, -1.000000, -1.000000, -0.000000)
dp4 r2.z, r4.xyzw, r5.xyzw
add r2.y, -r2.z, r2.y
mad r2.y, r3.x, r2.y, r2.z
add r4.xyzw, r1.xyzw, l(1.000000, 0.000000, 0.000000, 1.000000)

#line 76
mul r4.xyzw, r4.xyzw, l(0.097300, 0.103000, 0.109900, 0.103100)
frc r4.xyzw, r4.xyzw  // r4.x <- p4.z; r4.y <- p4.y; r4.z <- p4.w; r4.w <- p4.x

#line 77
add r5.xyzw, r4.zxwy, l(19.190001, 19.190001, 19.190001, 19.190001)
dp4 r2.z, r4.wyxz, r5.xyzw
add r4.xyzw, r2.zzzz, r4.xyzw

#line 78
add r5.xyzw, r4.yxxz, r4.wwyx
mul r4.xyzw, r4.xyzw, r5.xyzw
frc r4.xyzw, r4.xyzw  // r4.x <- <hash44_id199 return value>.x; r4.y <- <hash44_id199 return value>.y; r4.z <- <hash44_id199 return value>.z; r4.w <- <hash44_id199 return value>.w

#line 85
mad r4.xyzw, r4.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(-1.000000, -1.000000, -1.000000, -1.000000)
add r5.xyzw, r0.xyzw, l(-1.000000, -0.000000, -1.000000, -0.000000)
dp4 r2.z, r4.xyzw, r5.xyzw
add r4.xyzw, r1.xyzw, l(1.000000, 0.000000, 0.000000, 0.000000)

#line 76
mul r4.xyzw, r4.xyzw, l(0.097300, 0.103000, 0.109900, 0.103100)
frc r4.xyzw, r4.xyzw  // r4.x <- p4.z; r4.y <- p4.y; r4.z <- p4.w; r4.w <- p4.x

#line 77
add r5.xyzw, r4.zxwy, l(19.190001, 19.190001, 19.190001, 19.190001)
dp4 r2.w, r4.wyxz, r5.xyzw
add r4.xyzw, r2.wwww, r4.xyzw

#line 78
add r5.xyzw, r4.yxxz, r4.wwyx
mul r4.xyzw, r4.xyzw, r5.xyzw
frc r4.xyzw, r4.xyzw  // r4.x <- <hash44_id199 return value>.x; r4.y <- <hash44_id199 return value>.y; r4.z <- <hash44_id199 return value>.z; r4.w <- <hash44_id199 return value>.w

#line 85
mad r4.xyzw, r4.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(-1.000000, -1.000000, -1.000000, -1.000000)
add r5.xyzw, r0.xyzw, l(-0.000000, -0.000000, -1.000000, -0.000000)
dp4 r2.w, r4.xyzw, r5.xyzw
add r2.z, -r2.w, r2.z
mad r2.z, r3.x, r2.z, r2.w
add r2.y, -r2.z, r2.y
mad r2.y, r3.y, r2.y, r2.z
add r4.xyzw, r1.xyzw, l(0.000000, 1.000000, 0.000000, 1.000000)

#line 76
mul r4.xyzw, r4.xyzw, l(0.097300, 0.103000, 0.109900, 0.103100)
frc r4.xyzw, r4.xyzw  // r4.x <- p4.z; r4.y <- p4.y; r4.z <- p4.w; r4.w <- p4.x

#line 77
add r5.xyzw, r4.zxwy, l(19.190001, 19.190001, 19.190001, 19.190001)
dp4 r2.z, r4.wyxz, r5.xyzw
add r4.xyzw, r2.zzzz, r4.xyzw

#line 78
add r5.xyzw, r4.yxxz, r4.wwyx
mul r4.xyzw, r4.xyzw, r5.xyzw
frc r4.xyzw, r4.xyzw  // r4.x <- <hash44_id199 return value>.x; r4.y <- <hash44_id199 return value>.y; r4.z <- <hash44_id199 return value>.z; r4.w <- <hash44_id199 return value>.w

#line 85
mad r4.xyzw, r4.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(-1.000000, -1.000000, -1.000000, -1.000000)
add r5.xyzw, r0.xyzw, l(-1.000000, -1.000000, -0.000000, -0.000000)
dp4 r2.z, r4.xyzw, r5.xyzw
add r4.xyzw, r1.xyzw, l(0.000000, 1.000000, 0.000000, 0.000000)

#line 76
mul r4.xyzw, r4.xyzw, l(0.097300, 0.103000, 0.109900, 0.103100)
frc r4.xyzw, r4.xyzw  // r4.x <- p4.z; r4.y <- p4.y; r4.z <- p4.w; r4.w <- p4.x

#line 77
add r5.xyzw, r4.zxwy, l(19.190001, 19.190001, 19.190001, 19.190001)
dp4 r2.w, r4.wyxz, r5.xyzw
add r4.xyzw, r2.wwww, r4.xyzw

#line 78
add r5.xyzw, r4.yxxz, r4.wwyx
mul r4.xyzw, r4.xyzw, r5.xyzw
frc r4.xyzw, r4.xyzw  // r4.x <- <hash44_id199 return value>.x; r4.y <- <hash44_id199 return value>.y; r4.z <- <hash44_id199 return value>.z; r4.w <- <hash44_id199 return value>.w

#line 85
mad r4.xyzw, r4.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(-1.000000, -1.000000, -1.000000, -1.000000)
add r5.xyzw, r0.xyzw, l(-0.000000, -1.000000, -0.000000, -0.000000)
dp4 r2.w, r4.xyzw, r5.xyzw
add r2.z, -r2.w, r2.z
mad r2.z, r3.x, r2.z, r2.w
add r4.xyzw, r1.xyzw, l(0.000000, 0.000000, 0.000000, 1.000000)

#line 76
mul r1.xyzw, r1.xyzw, l(0.097300, 0.103000, 0.109900, 0.103100)
frc r1.xyzw, r1.xyzw  // r1.x <- p4.z; r1.y <- p4.y; r1.z <- p4.w; r1.w <- p4.x
mul r4.xyzw, r4.xyzw, l(0.097300, 0.103000, 0.109900, 0.103100)
frc r4.xyzw, r4.xyzw  // r4.x <- p4.z; r4.y <- p4.y; r4.z <- p4.w; r4.w <- p4.x; r4.x <- p4.z; r4.y <- p4.y; r4.z <- p4.w; r4.w <- p4.x

#line 77
add r5.xyzw, r4.zxwy, l(19.190001, 19.190001, 19.190001, 19.190001)
dp4 r2.w, r4.wyxz, r5.xyzw
add r4.xyzw, r2.wwww, r4.xyzw

#line 78
add r5.xyzw, r4.yxxz, r4.wwyx
mul r4.xyzw, r4.xyzw, r5.xyzw
frc r4.xyzw, r4.xyzw  // r4.x <- <hash44_id199 return value>.x; r4.y <- <hash44_id199 return value>.y; r4.z <- <hash44_id199 return value>.z; r4.w <- <hash44_id199 return value>.w; r4.x <- <hash44_id199 return value>.x; r4.y <- <hash44_id199 return value>.y; r4.z <- <hash44_id199 return value>.z; r4.w <- <hash44_id199 return value>.w

#line 85
mad r4.xyzw, r4.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(-1.000000, -1.000000, -1.000000, -1.000000)
add r5.xyzw, r0.xyzw, l(-1.000000, -0.000000, -0.000000, -0.000000)
dp4 r2.w, r4.xyzw, r5.xyzw

#line 77
add r4.xyzw, r1.zxwy, l(19.190001, 19.190001, 19.190001, 19.190001)
dp4 r4.x, r1.wyxz, r4.xyzw
add r1.xyzw, r1.xyzw, r4.xxxx  // r1.x <- p4.z; r1.y <- p4.y; r1.z <- p4.w; r1.w <- p4.x

#line 78
add r4.xyzw, r1.yxxz, r1.wwyx
mul r1.xyzw, r1.xyzw, r4.xyzw
frc r1.xyzw, r1.xyzw  // r1.x <- <hash44_id199 return value>.x; r1.y <- <hash44_id199 return value>.y; r1.z <- <hash44_id199 return value>.z; r1.w <- <hash44_id199 return value>.w

#line 85
mad r1.xyzw, r1.xyzw, l(2.000000, 2.000000, 2.000000, 2.000000), l(-1.000000, -1.000000, -1.000000, -1.000000)
dp4 r0.x, r1.xyzw, r0.xyzw
add r0.y, -r0.x, r2.w
mad r0.x, r3.x, r0.y, r0.x
add r0.y, -r0.x, r2.z
mad r0.x, r3.y, r0.y, r0.x
add r0.y, -r0.x, r2.y
mad r0.x, r3.z, r0.y, r0.x
add r0.y, -r0.x, r2.x
mad r0.x, r3.w, r0.y, r0.x

#line 138
lt r0.y, l(0.000000), r0.x
lt r0.z, r0.x, l(0.000000)

#line 85
add r0.x, r0.x, r0.x  // r0.x <- <gradientNoise_id213 return value>

#line 140
min r0.x, |r0.x|, l(1.000000)  // r0.x <- saturate_3689651559

#line 138
iadd r0.y, -r0.y, r0.z
itof r0.y, r0.y  // r0.y <- sign_767907005

#line 99
add r0.z, -r0.x, l(1.000000)  // r0.z <- result_4162530266

#line 97
div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), |cb0[2].w|  // r0.w <- result_8832483

#line 98
add r0.w, r0.w, l(-2.000000)  // r0.w <- result_3553001757

#line 101
mad r0.w, r0.w, r0.z, l(1.000000)  // r0.w <- result_4136880795

#line 102
div r0.w, r0.x, r0.w  // r0.w <- result_2420006788

#line 103
add r0.w, -r0.w, l(1.000000)  // r0.w <- result_3995171476

#line 104
div r1.x, l(1.000000, 1.000000, 1.000000, 1.000000), cb0[2].w  // r1.x <- result_1754732624

#line 105
add r1.x, r1.x, l(-2.000000)  // r1.x <- result_4179827015

#line 108
mad r0.z, r1.x, r0.z, l(1.000000)  // r0.z <- result_2928390460

#line 109
div r0.x, r0.x, r0.z  // r0.x <- result_1881175435

#line 95
lt r0.z, l(0.000000), cb0[2].w  // r0.z <- Assign_4186034371

#line 110
movc r0.x, r0.z, r0.x, r0.w  // r0.x <- expression_3834703806

#line 142
mul r0.x, r0.x, r0.y  // r0.x <- result_2900412290

#line 144
mad r0.x, r0.x, cb0[3].x, cb0[3].y  // r0.x <- result_2452738565

#line 145
add r0.x, r0.x, l(1.000000)  // r0.x <- result_2457669475

#line 146
mul r0.x, r0.x, cb0[3].z

#line 147
mul r0.y, r0.x, l(0.500000)  // r0.y <- result_3583968935

#line 148
mad r0.x, -r0.x, l(0.500000), cb0[3].w
mad_sat r0.y, cb0[4].x, r0.x, r0.y  // r0.y <- saturate_3364515360.y

#line 175
mov_sat r0.xz, l(0,0,0,0)  // r0.z <- saturate_3364515360.x

#line 120
mad r1.xyz, r0.zyzz, l(0.305306, 0.305306, 0.305306, 0.000000), l(0.682171, 0.682171, 0.682171, 0.000000)
mad r1.xyz, r0.zyzz, r1.xyzx, l(0.012523, 0.012523, 0.012523, 0.000000)
mul o0.xyz, r0.xyzx, r1.xyzx

#line 180
mov o0.w, l(1.000000)
ret 
// Approximately 258 instruction slots used
***************************
*************************/
static const float PI_id17 = 3.1415926535897;
struct PS_STREAMS 
{
    float4 Position_id14;
    float3 PPosition_id55;
    float4 ColorTarget_id2;
};
struct PS_OUTPUT 
{
    float4 ColorTarget_id2 : SV_Target0;
};
struct PS_INPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float4 Position_id14 : POSITION;
    float3 PPosition_id55 : PPOSITION;
};
struct VS_STREAMS 
{
    float4 Position_id14;
    float3 PPosition_id55;
    float4 PositionWS_id15;
    float4 ShadingPosition_id0;
};
struct VS_OUTPUT 
{
    float4 ShadingPosition_id0 : SV_Position;
    float4 Position_id14 : POSITION;
    float3 PPosition_id55 : PPOSITION;
};
struct VS_INPUT 
{
    float4 Position_id14 : POSITION;
    float3 PPosition_id55 : PPOSITION;
};
struct Matrix4x4 
{
    float4x4 Matrix;
};
cbuffer Inputs 
{
    float input_2345886612_id45;
    float input_2340563897_id46;
    float3 input_839765076_id47;
    float3 input_2391782587_id48;
    float input_157705887_id49;
    float input_507318587_id50;
    float input_2135914162_id51;
    float input_942655201_id52;
    float input_1965808618_id53;
    float input_1408606897_id54;
};
cbuffer PerDraw 
{
    float4x4 World_id33;
    float4x4 WorldInverse_id34;
    float4x4 WorldInverseTranspose_id35;
    float4x4 WorldView_id36;
    float4x4 WorldViewInverse_id37;
    float4x4 WorldViewProjection_id38;
    float3 WorldScale_id39;
    float4 EyeMS_id40;
};
cbuffer PerView 
{
    float4x4 View_id26;
    float4x4 ViewInverse_id27;
    float4x4 Projection_id28;
    float4x4 ProjectionInverse_id29;
    float4x4 ViewProjection_id30;
    float2 ProjScreenRay_id31;
    float4 Eye_id32;
};
float4 hash44_id199(float4 p4)
{
    p4 = frac(p4 * float4(.1031, .1030, .0973, .1099));
    p4 += dot(p4, p4.wzxy + 19.19);
    return frac((p4.xxyz + p4.yzzw) * p4.zywx);
}
float gradientNoise_id213(float4 p)
{
    float4 i = floor(p);
    float4 f = frac(p);
    float4 u = f * f * (3.0 - 2.0 * f);
    return 2 * lerp(lerp(lerp(lerp(dot(hash44_id199(i + float4(0, 0, 0, 0)) * 2.0 - 1.0, f - float4(0, 0, 0, 0)), dot(hash44_id199(i + float4(1, 0, 0, 0)) * 2.0 - 1.0, f - float4(1, 0, 0, 0)), u.x), lerp(dot(hash44_id199(i + float4(0, 1, 0, 0)) * 2.0 - 1.0, f - float4(0, 1, 0, 0)), dot(hash44_id199(i + float4(1, 1, 0, 0)) * 2.0 - 1.0, f - float4(1, 1, 0, 0)), u.x), u.y), lerp(lerp(dot(hash44_id199(i + float4(0, 0, 1, 0)) * 2.0 - 1.0, f - float4(0, 0, 1, 0)), dot(hash44_id199(i + float4(1, 0, 1, 0)) * 2.0 - 1.0, f - float4(1, 0, 1, 0)), u.x), lerp(dot(hash44_id199(i + float4(0, 1, 1, 0)) * 2.0 - 1.0, f - float4(0, 1, 1, 0)), dot(hash44_id199(i + float4(1, 1, 1, 0)) * 2.0 - 1.0, f - float4(1, 1, 1, 0)), u.x), u.y), u.z), lerp(lerp(lerp(dot(hash44_id199(i + float4(0, 0, 0, 1)) * 2.0 - 1.0, f - float4(0, 0, 0, 1)), dot(hash44_id199(i + float4(1, 0, 0, 1)) * 2.0 - 1.0, f - float4(1, 0, 0, 1)), u.x), lerp(dot(hash44_id199(i + float4(0, 1, 0, 1)) * 2.0 - 1.0, f - float4(0, 1, 0, 1)), dot(hash44_id199(i + float4(1, 1, 0, 1)) * 2.0 - 1.0, f - float4(1, 1, 0, 1)), u.x), u.y), lerp(lerp(dot(hash44_id199(i + float4(0, 0, 1, 1)) * 2.0 - 1.0, f - float4(0, 0, 1, 1)), dot(hash44_id199(i + float4(1, 0, 1, 1)) * 2.0 - 1.0, f - float4(1, 0, 1, 1)), u.x), lerp(dot(hash44_id199(i + float4(0, 1, 1, 1)) * 2.0 - 1.0, f - float4(0, 1, 1, 1)), dot(hash44_id199(i + float4(1, 1, 1, 1)) * 2.0 - 1.0, f - float4(1, 1, 1, 1)), u.x), u.y), u.z), u.w);
}
float map_id137(float input, float InMin, float InMax, float OutMin, float OutMax)
{
    float range = InMax - InMin;
    float normalized = (input - InMin) / range;
    return OutMin + normalized * (OutMax - OutMin);
}
float Function_4108537353_id366(in float arg_0)
{
    bool Assign_4186034371 = input_157705887_id49 > 0;
    float abs_3270830054 = abs(input_157705887_id49);
    float result_8832483 = (1 / abs_3270830054);
    float result_3553001757 = (result_8832483 - 2);
    float result_4162530266 = (1 - arg_0);
    float result_795608133 = (result_3553001757 * result_4162530266);
    float result_4136880795 = (result_795608133 + 1);
    float result_2420006788 = (arg_0 / result_4136880795);
    float result_3995171476 = (1 - result_2420006788);
    float result_1754732624 = (1 / input_157705887_id49);
    float result_4179827015 = (result_1754732624 - 2);
    float result_2902261264 = (1 - arg_0);
    float result_3017872282 = (result_4179827015 * result_2902261264);
    float result_2928390460 = (result_3017872282 + 1);
    float result_1881175435 = (arg_0 / result_2928390460);
    float expression_3834703806 = Assign_4186034371 ? result_1881175435 : result_3995171476;
    return expression_3834703806;
}
float gradientNoise14_id305(float4 p)
{
    return gradientNoise_id213(p);
}
float4 SRGBToLinear_id97(float4 sRGBa)
{
    float3 sRGB = sRGBa.rgb;
    return float4(sRGB * (sRGB * (sRGB * 0.305306011 + 0.682171111) + 0.012522878), sRGBa.a);
}
float3 map_id142(float3 input, float3 InMin, float3 InMax, float3 OutMin, float3 OutMax)
{
    float3 vec;
    vec.x = map_id137(input.x, InMin.x, InMax.x, OutMin.x, OutMax.x);
    vec.y = map_id137(input.y, InMin.y, InMax.y, OutMin.y, OutMax.y);
    vec.z = map_id137(input.z, InMin.z, InMax.z, OutMin.z, OutMax.z);
    return vec;
}
float3 Function_4154367924_id367(inout PS_STREAMS streams, in float3 arg_0)
{
    float4 join_3026951851 = float4(streams.PPosition_id55, input_2340563897_id46);
    float4 join_2894320677 = float4(input_839765076_id47, 1);
    float4 result_4144747945 = (join_3026951851 * join_2894320677);
    float4 join_841893888 = float4(input_2391782587_id48, 0);
    float4 result_1273172016 = (result_4144747945 + join_841893888);
    float gradientNoise14_2128404583 = gradientNoise14_id305(result_1273172016);
    float sign_767907005 = sign(gradientNoise14_2128404583);
    float abs_2626207825 = abs(gradientNoise14_2128404583);
    float saturate_3689651559 = saturate(abs_2626207825);
    float Invoke_2732807596 = Function_4108537353_id366(saturate_3689651559);
    float result_2900412290 = (sign_767907005 * Invoke_2732807596);
    float result_2615028532 = (result_2900412290 * input_507318587_id50);
    float result_2452738565 = (result_2615028532 + input_2135914162_id51);
    float result_2457669475 = (result_2452738565 + 1);
    float result_1911027417 = (result_2457669475 * 0.5);
    float result_3583968935 = (result_1911027417 * input_942655201_id52);
    float lerp_974371589 = lerp(result_3583968935, input_1965808618_id53, input_1408606897_id54);
    float3 Float3Join_2771374576 = float3(0, lerp_974371589, 0);
    return Float3Join_2771374576;
}
float3 rY_id61(float3 p, float a)
{
    a *= 6.2831854820251465;
    float c, s;
    float3 q = p;
    c = cos(a);
    s = sin(a);
    p.x = c * q.x + s * q.z;
    p.z = -s * q.x + c * q.z;
    return p;
}
PS_OUTPUT PSMain(PS_INPUT __input__)
{
    PS_STREAMS streams = (PS_STREAMS)0;
    streams.Position_id14 = __input__.Position_id14;
    streams.PPosition_id55 = __input__.PPosition_id55;
    float3 PositionXyz_381821212 = streams.Position_id14.xyz;
    float3 Invoke_2179550631 = Function_4154367924_id367(streams, PositionXyz_381821212);
    float4 ToFloat_245027105 = float4(Invoke_2179550631.xyz, 1.0);
    float3 ToFloatXyz_1817576498 = ToFloat_245027105.xyz;
    float3 map_2822352833 = map_id142(ToFloatXyz_1817576498, float3(0, 0, 0), float3(1, 1, 1), float3(0, 0, 0), float3(1, 1, 1));
    float ToFloatW_3621303902 = ToFloat_245027105.w;
    float4 join_1732849673 = float4(map_2822352833, ToFloatW_3621303902);
    float4 saturate_3364515360 = saturate(join_1732849673);
    float4 SRGBToLinear_3513180466 = SRGBToLinear_id97(saturate_3364515360);
    streams.ColorTarget_id2 = SRGBToLinear_3513180466;
    PS_OUTPUT __output__ = (PS_OUTPUT)0;
    __output__.ColorTarget_id2 = streams.ColorTarget_id2;
    return __output__;
}
VS_OUTPUT VSMain(VS_INPUT __input__)
{
    VS_STREAMS streams = (VS_STREAMS)0;
    streams.Position_id14 = __input__.Position_id14;
    streams.PPosition_id55 = __input__.PPosition_id55;
    float3 PositionXyz_1361415901 = streams.Position_id14.xyz;
    float3 rY_4146808450 = rY_id61(PositionXyz_1361415901, input_2345886612_id45);
    float4 join_2831693890 = float4(rY_4146808450, 1);
    streams.PositionWS_id15 = join_2831693890;
    float4 mul_3077879278 = mul(join_2831693890, WorldViewProjection_id38);
    streams.ShadingPosition_id0 = mul_3077879278;
    VS_OUTPUT __output__ = (VS_OUTPUT)0;
    __output__.ShadingPosition_id0 = streams.ShadingPosition_id0;
    __output__.Position_id14 = streams.Position_id14;
    __output__.PPosition_id55 = streams.PPosition_id55;
    return __output__;
}
