/**************************
***** Compiler Parameters *****
***************************
@P EffectName: ComputeFXEffect
@P   - ComputeEffectShader.ThreadNumbers: X:64 Y:1 Z:1
@P EffectNodeBase.EffectNodeBaseShader: mixin ComputeFXGraph [{Root = mixin ComputeOrder [{Computes = [Shader_12045780]}]}]
***************************
****  ConstantBuffers  ****
***************************
cbuffer PerDispatch [Size: 272]
@C    ThreadGroupCountGlobal_id10 => ComputeShaderBase.ThreadGroupCountGlobal
@C    input_2496523869_id17 => input_2496523869
@C    input_920095884_id18 => input_920095884
@C    input_989038992_id19 => input_989038992
@C    input_173026838_id20 => input_173026838
@C    input_1387116872_id21 => input_1387116872
@C    input_3802034477_id22 => input_3802034477
@C    input_991319651_id23 => input_991319651
@C    input_2338594544_id24 => input_2338594544
@C    input_3199443795_id25 => input_3199443795
@C    input_1431867861_id26 => input_1431867861
@C    input_242503097_id27 => input_242503097
@C    input_4114012044_id28 => input_4114012044
@C    input_1873120750_id29 => input_1873120750
@C    input_1379401097_id30 => input_1379401097
@C    input_675538939_id31 => input_675538939
@C    input_3418410476_id32 => input_3418410476
@C    input_172824530_id33 => input_172824530
@C    input_1827514650_id34 => input_1827514650
***************************
******  Resources    ******
***************************
@R    SamplerInput_2277027595_id14 => SamplerInput_2277027595 [Stage: Compute, Slot: (0-0)]
@R    TextureInput_3485594508_id13 => TextureInput_3485594508 [Stage: Compute, Slot: (0-0)]
@R    DynamicBufferInput_1283011543_id12 => DynamicBufferInput_1283011543 [Stage: Compute, Slot: (0-0)]
@R    DynamicBufferInput_58384011_id15 => DynamicBufferInput_58384011 [Stage: Compute, Slot: (1-1)]
@R    DynamicBufferInput_1492965403_id16 => DynamicBufferInput_1492965403 [Stage: Compute, Slot: (2-2)]
@R    PerDispatch => PerDispatch [Stage: Compute, Slot: (0-0)]
***************************
*****     Sources     *****
***************************
@S    ComputeShaderBase => 8f045851eaa4513eb38a704d53889e6d
@S    ComputeFXGraph => dca3deb94a1ea6d5babe444153dee98b
@S    ComputeVoid => b62583a94b8503c79e9107f4b5bc9392
@S    ComputeOrder => 1d9b1cd3f5e3ad3f3f10e4fc88326cc7
@S    Shader_12045780 => 7436c610463e9c50434e087f4be874aa
@S    FuseCoreBaseCast => 1273a005630aadfff132dcc52db04833
@S    FuseCoreMathPCG => e529e3d6e7220073ba1b2dacab9e88b2
***************************
*****     Stages      *****
***************************
@G    Compute => 704e580f117445c51ec7e9bfc805dc2a
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer PerDispatch
// {
//
//   int3 ThreadGroupCountGlobal_id10;  // Offset:    0 Size:    12 [unused]
//   int input_2496523869_id17;         // Offset:   12 Size:     4
//   int input_920095884_id18;          // Offset:   16 Size:     4
//   int input_989038992_id19;          // Offset:   20 Size:     4
//   float3 input_173026838_id20;       // Offset:   32 Size:    12
//   float3 input_1387116872_id21;      // Offset:   48 Size:    12
//   int input_3802034477_id22;         // Offset:   60 Size:     4
//   int input_991319651_id23;          // Offset:   64 Size:     4
//   float4x4 input_2338594544_id24;    // Offset:   80 Size:    64
//   float input_3199443795_id25;       // Offset:  144 Size:     4
//   float input_1431867861_id26;       // Offset:  148 Size:     4 [unused]
//   float3 input_242503097_id27;       // Offset:  160 Size:    12 [unused]
//   float4x4 input_4114012044_id28;    // Offset:  176 Size:    64
//   float3 input_1873120750_id29;      // Offset:  240 Size:    12
//   float input_1379401097_id30;       // Offset:  252 Size:     4
//   float input_675538939_id31;        // Offset:  256 Size:     4
//   float input_3418410476_id32;       // Offset:  260 Size:     4
//   int input_172824530_id33;          // Offset:  264 Size:     4
//   int input_1827514650_id34;         // Offset:  268 Size:     4
//
// }
//
// Resource bind info for DynamicBufferInput_1283011543_id12
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
// Resource bind info for DynamicBufferInput_58384011_id15
// {
//
//   struct PSystem
//   {
//       
//       float Age;                     // Offset:    0
//       float LifeTime;                // Offset:    4
//       int Id;                        // Offset:    8
//       float3 PPosition;              // Offset:   12
//       float3 Velocity;               // Offset:   24
//       float Size;                    // Offset:   36
//       float Mass;                    // Offset:   40
//       float4 PColor;                 // Offset:   44
//       int Cycle;                     // Offset:   60
//       float3 Target;                 // Offset:   64
//       float3 Size3;                  // Offset:   76
//       float3 AxisX;                  // Offset:   88
//       float3 AxisY;                  // Offset:  100
//       float3 AxisZ;                  // Offset:  112
//
//   } $Element;                        // Offset:    0 Size:   124
//
// }
//
// Resource bind info for DynamicBufferInput_1492965403_id16
// {
//
//   int $Element;                      // Offset:    0 Size:     4
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// SamplerInput_2277027595_id14      sampler      NA          NA             s0      1 
// TextureInput_3485594508_id13      texture  float4          2d             t0      1 
// DynamicBufferInput_1283011543_id12        UAV  struct         r/w             u0      1 
// DynamicBufferInput_58384011_id15        UAV  struct         r/w             u1      1 
// DynamicBufferInput_1492965403_id16        UAV  struct     consume             u2      1 
// PerDispatch                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer CB0[17], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t0
dcl_uav_structured u0, 4
dcl_uav_structured u1, 124
dcl_uav_structured u2, 4
dcl_input vThreadID.x
dcl_temps 5
dcl_thread_group 64, 1, 1
//
// Initial variable locations:
//   vThreadGroupID.x <- __input__.GroupId_id0.x; vThreadGroupID.y <- __input__.GroupId_id0.y; vThreadGroupID.z <- __input__.GroupId_id0.z; 
//   vThreadID.x <- __input__.DispatchThreadId_id1.x; vThreadID.y <- __input__.DispatchThreadId_id1.y; vThreadID.z <- __input__.DispatchThreadId_id1.z
//
#line 83 "C:\Projects\MOTF\MOTF_VVVV_6.3\vvvv_gamma_6.3\log\shader_ComputeFXEffect_f2f6873762d15495d00400f4ba15a174.hlsl"
ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.x, l(1), l(0), u0.xxxx  // r0.x <- getBuffer_1293734944

#line 84
imin r0.x, r0.x, cb0[0].w  // r0.x <- min_3786332730

#line 90
ult r0.x, vThreadID.x, r0.x
if_nz r0.x

#line 71
  imul null, r0.x, vThreadID.x, l(0x0019660d)
  imul null, r0.yz, cb0[1].xxyx, l(0, 0x0019660d, 0x0019660d, 0)
  iadd r0.xyz, r0.xyzx, l(0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f, 0)  // r0.x <- v.x; r0.y <- v.y; r0.z <- v.z

#line 72
  imad r1.x, r0.y, r0.z, r0.x  // r1.x <- v.x

#line 73
  imad r1.y, r0.z, r1.x, r0.y  // r1.y <- v.y

#line 74
  imad r1.z, r1.x, r1.y, r0.z  // r1.z <- v.z

#line 75
  ushr r0.xyz, r1.xyzx, l(16, 16, 16, 0)
  xor r0.xyz, r0.xyzx, r1.xyzx  // r0.x <- v.x; r0.y <- v.y; r0.z <- v.z

#line 76
  imad r0.x, r0.y, r0.z, r0.x

#line 79
  utof r0.x, r0.x
  mul r0.x, r0.x, l(0.000000)  // r0.x <- <pcg3d_id5 return value>.x

#line 71
  imul null, r1.x, vThreadID.x, l(0x0019660d)
  imul null, r1.y, cb0[3].w, l(0x0019660d)
  imul null, r1.z, cb0[4].x, l(0x0019660d)
  iadd r0.yzw, r1.xxyz, l(0, 0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f)  // r0.y <- v.x; r0.z <- v.y; r0.w <- v.z

#line 72
  imad r1.x, r0.z, r0.w, r0.y  // r1.x <- v.x

#line 73
  imad r1.y, r0.w, r1.x, r0.z  // r1.y <- v.y

#line 74
  imad r1.z, r1.x, r1.y, r0.w  // r1.z <- v.z

#line 75
  ushr r0.yzw, r1.xxyz, l(0, 16, 16, 16)
  xor r0.yzw, r0.yyzw, r1.xxyz  // r0.y <- v.x; r0.z <- v.y; r0.w <- v.z

#line 76
  imad r0.y, r0.z, r0.w, r0.y

#line 77
  imad r0.z, r0.w, r0.y, r0.z

#line 78
  imad r0.w, r0.y, r0.z, r0.w

#line 79
  utof r1.xyz, r0.yzwy
  mul r0.yzw, r1.xxyz, l(0.000000, 0.000000, 0.000000, 0.000000)  // r0.y <- <pcg3d_id5 return value>.x; r0.z <- <pcg3d_id5 return value>.y; r0.w <- <pcg3d_id5 return value>.z

#line 96
  add r1.xyz, -cb0[2].xyzx, cb0[3].xyzx
  mad r1.yzw, r0.yyzw, r1.xxyz, cb0[2].xxyz  // r1.y <- lerp_3535887589.x; r1.z <- lerp_3535887589.y; r1.w <- lerp_3535887589.z

#line 98
  mov r1.x, l(1.000000)
  dp4 r2.x, r1.yzwx, cb0[5].xyzw  // r2.x <- mul_2331623520.x
  dp4 r2.y, r1.yzwx, cb0[6].xyzw  // r2.y <- mul_2331623520.y

#line 101
  mad r0.yz, r2.xxyx, l(0.000000, 1.000000, -1.000000, 0.000000), l(0.000000, 0.500000, 0.500000, 0.000000)  // r0.y <- result_3730156672.x; r0.z <- result_3730156672.y

#line 103
  sample_l_indexable(texture2d)(float,float,float,float) r0.y, r0.yzyy, t0.yxzw, s0, l(0.000000)  // r0.y <- textureNode_727377111.x

#line 105
  add r0.y, -r0.y, l(1.000000)  // r0.y <- result_3933975961

#line 106
  mul r0.y, r0.y, cb0[9].x  // r0.y <- result_1238341587

#line 107
  lt r0.x, r0.x, r0.y  // r0.x <- Assign_3442837552

#line 108
  if_nz r0.x

#line 110
    imm_atomic_consume r0.x, u2
    ld_structured_indexable(structured_buffer, stride=4)(mixed,mixed,mixed,mixed) r0.z, r0.x, l(0), u2.xxxx  // r0.z <- consumeBuffer_2275858964

#line 113
    ld_structured_indexable(structured_buffer, stride=124)(mixed,mixed,mixed,mixed) r2.x, r0.z, l(60), u1.xxxx  // r2.x <- getBuffer_2805507595.Cycle

#line 133
    dp4 r0.w, r1.yzwx, cb0[11].xyzw  // r0.w <- mul_423312361.x
    dp4 r3.x, r1.yzwx, cb0[12].xyzw  // r3.x <- mul_423312361.y
    dp4 r3.y, r1.yzwx, cb0[13].xyzw  // r3.y <- mul_423312361.z

#line 71
    imul null, r4.x, vThreadID.x, l(0x0019660d)
    imul null, r4.yz, cb0[16].zzwz, l(0, 0x0019660d, 0x0019660d, 0)
    iadd r2.yzw, r4.xxyz, l(0, 0x3c6ef35f, 0x3c6ef35f, 0x3c6ef35f)  // r2.y <- v.x; r2.z <- v.y; r2.w <- v.z

#line 72
    imad r4.x, r2.z, r2.w, r2.y  // r4.x <- v.x

#line 73
    imad r4.y, r2.w, r4.x, r2.z  // r4.y <- v.y

#line 74
    imad r4.z, r4.x, r4.y, r2.w  // r4.z <- v.z

#line 75
    ushr r2.yzw, r4.xxyz, l(0, 16, 16, 16)
    xor r2.yzw, r2.yyzw, r4.xxyz  // r2.y <- v.x; r2.z <- v.y; r2.w <- v.z

#line 76
    imad r2.y, r2.z, r2.w, r2.y

#line 79
    utof r2.y, r2.y
    mul r2.y, r2.y, l(0.000000)  // r2.y <- <pcg3d_id5 return value>.x

#line 143
    add r2.z, -cb0[16].x, cb0[16].y
    mad r0.y, r2.y, r2.z, cb0[16].x  // r0.y <- lerp_2267442120

#line 146
    iadd r1.x, r2.x, l(1)  // r1.x <- result_416183477

#line 159
    mov r0.x, l(0.000010)
    store_structured u1.xyzw, r0.z, l(0), r0.xyzw
    mov r3.zw, cb0[15].xxxy
    store_structured u1.xyzw, r0.z, l(16), r3.xyzw
    mov r2.xy, cb0[15].zwzz
    mov r2.z, l(1.000000)
    store_structured u1.xyz, r0.z, l(32), r2.xyzx
    store_structured u1.xyzw, r0.z, l(60), r1.xyzw

#line 160
  endif 
endif 

#line 186
ret 
// Approximately 71 instruction slots used
***************************
*************************/
struct CS_STREAMS 
{
    uint3 GroupId_id0;
    uint3 DispatchThreadId_id1;
    int ThreadCountX_id7;
    int ThreadCountY_id8;
    int ThreadCountZ_id9;
    uint ThreadCountPerGroup_id5;
    uint3 ThreadGroupCount_id4;
    uint ThreadGroupIndex_id6;
};
struct CS_INPUT 
{
    uint3 GroupId_id0 : SV_GroupID;
    uint3 DispatchThreadId_id1 : SV_DispatchThreadID;
};
struct PSystem 
{
    float Age;
    float LifeTime;
    int Id;
    float3 PPosition;
    float3 Velocity;
    float Size;
    float Mass;
    float4 PColor;
    int Cycle;
    float3 Target;
    float3 Size3;
    float3 AxisX;
    float3 AxisY;
    float3 AxisZ;
};
cbuffer PerDispatch 
{
    int3 ThreadGroupCountGlobal_id10;
    int input_2496523869_id17;
    int input_920095884_id18;
    int input_989038992_id19;
    float3 input_173026838_id20;
    float3 input_1387116872_id21;
    int input_3802034477_id22;
    int input_991319651_id23;
    float4x4 input_2338594544_id24;
    float input_3199443795_id25;
    float input_1431867861_id26;
    float3 input_242503097_id27;
    float4x4 input_4114012044_id28;
    float3 input_1873120750_id29;
    float input_1379401097_id30;
    float input_675538939_id31;
    float input_3418410476_id32;
    int input_172824530_id33;
    int input_1827514650_id34;
};
RWStructuredBuffer<int> DynamicBufferInput_1283011543_id12;
Texture2D<float4> TextureInput_3485594508_id13;
SamplerState SamplerInput_2277027595_id14;
RWStructuredBuffer<PSystem> DynamicBufferInput_58384011_id15;
ConsumeStructuredBuffer<int> DynamicBufferInput_1492965403_id16;
float3 cast33_id7(float3 p)
{
    return p;
}
float cast13_id6(float3 p)
{
    return p.x;
}
float3 pcg3d_id5(uint3 v)
{
    v = v * 1664525 + 1013904223;
    v.x += v.y * v.z;
    v.y += v.z * v.x;
    v.z += v.x * v.y;
    v = v ^ (v >> 16);
    v.x += v.y * v.z;
    v.y += v.z * v.x;
    v.z += v.x * v.y;
    return float3(v) * (1.0 / float(0xffffffff));
}
void Compute_id4(inout CS_STREAMS streams)
{
    int getBuffer_1293734944 = DynamicBufferInput_1283011543_id12[1];
    int min_3786332730 = min(input_2496523869_id17, getBuffer_1293734944);
    bool Assign_1045685193 = streams.DispatchThreadId_id1.x >= min_3786332730;
    if (Assign_1045685193)
    {
        return;
    }
    int3 Int3Join_2667512879 = int3(streams.DispatchThreadId_id1.x, input_920095884_id18, input_989038992_id19);
    float3 pcg3d_3524058455 = pcg3d_id5(Int3Join_2667512879);
    float cast13_820808377 = cast13_id6(pcg3d_3524058455);
    int3 Int3Join_782418546 = int3(streams.DispatchThreadId_id1.x, input_3802034477_id22, input_991319651_id23);
    float3 pcg3d_124627850 = pcg3d_id5(Int3Join_782418546);
    float3 cast33_891390384 = cast33_id7(pcg3d_124627850);
    float3 lerp_3535887589 = lerp(input_173026838_id20, input_1387116872_id21, cast33_891390384);
    float4 join_1067257261 = float4(lerp_3535887589, 1);
    float4 mul_2331623520 = mul(join_1067257261, input_2338594544_id24);
    float3 mulXyz_4104147907 = mul_2331623520.xyz;
    float3 result_2303852537 = (mulXyz_4104147907 * float3(1, -1, 1));
    float3 result_3730156672 = (result_2303852537 + float3(0.5, 0.5, 0.5));
    float2 resultXy_1918803761 = result_3730156672.xy;
    float4 textureNode_727377111 = TextureInput_3485594508_id13.SampleLevel(SamplerInput_2277027595_id14, resultXy_1918803761, 0);
    float textureNodeX_3090503918 = textureNode_727377111.x;
    float result_3933975961 = (1 - textureNodeX_3090503918);
    float result_1238341587 = (result_3933975961 * input_3199443795_id25);
    bool Assign_3442837552 = cast13_820808377 < result_1238341587;
    if (Assign_3442837552)
    {
        int consumeBuffer_2275858964 = DynamicBufferInput_1492965403_id16.Consume();
        int3 Int3Join_3452399409 = int3(consumeBuffer_2275858964, 0, 0);
        int IndexX_2446700840 = Int3Join_3452399409.x;
        PSystem getBuffer_2805507595 = DynamicBufferInput_58384011_id15[IndexX_2446700840];
        int id_2090133185 = getBuffer_2805507595.Id;
        float3 pposition_2640105079 = getBuffer_2805507595.PPosition;
        float3 velocity_1924730669 = getBuffer_2805507595.Velocity;
        float size_1624637747 = getBuffer_2805507595.Size;
        float mass_1172772430 = getBuffer_2805507595.Mass;
        float4 pcolor_2414973900 = getBuffer_2805507595.PColor;
        float lifetime_2336258130 = getBuffer_2805507595.LifeTime;
        float age_3578459600 = getBuffer_2805507595.Age;
        int cycle_3595310678 = getBuffer_2805507595.Cycle;
        float3 target_2150288829 = getBuffer_2805507595.Target;
        float deltatime_3709624456 = 0;
        deltatime_3709624456 = input_1431867861_id26;
        int3 index_3722343075 = int3(0, 0, 0);
        index_3722343075 = Int3Join_3452399409;
        float3 resourcescale_22180690 = float3(0, 0, 0);
        resourcescale_22180690 = input_242503097_id27;
        int IndexX_3692059187 = Int3Join_3452399409.x;
        id_2090133185 = IndexX_3692059187;
        float4 join_1933226188 = float4(lerp_3535887589, 1);
        float4 mul_423312361 = mul(join_1933226188, input_4114012044_id28);
        float3 mulXyz_67681978 = mul_423312361.xyz;
        pposition_2640105079 = mulXyz_67681978;
        velocity_1924730669 = input_1873120750_id29;
        size_1624637747 = input_1379401097_id30;
        mass_1172772430 = 1;
        pcolor_2414973900 = pcolor_2414973900;
        int3 Int3Join_3420553147 = int3(streams.DispatchThreadId_id1.x, input_172824530_id33, input_1827514650_id34);
        float3 pcg3d_342194755 = pcg3d_id5(Int3Join_3420553147);
        float cast13_1540593413 = cast13_id6(pcg3d_342194755);
        float lerp_2267442120 = lerp(input_675538939_id31, input_3418410476_id32, cast13_1540593413);
        lifetime_2336258130 = lerp_2267442120;
        age_3578459600 = 1E-05;
        int result_416183477 = (cycle_3595310678 + 1);
        cycle_3595310678 = result_416183477;
        target_2150288829 = lerp_3535887589;
        getBuffer_2805507595.Id = id_2090133185;
        getBuffer_2805507595.PPosition = pposition_2640105079;
        getBuffer_2805507595.Velocity = velocity_1924730669;
        getBuffer_2805507595.Size = size_1624637747;
        getBuffer_2805507595.Mass = mass_1172772430;
        getBuffer_2805507595.PColor = pcolor_2414973900;
        getBuffer_2805507595.LifeTime = lifetime_2336258130;
        getBuffer_2805507595.Age = age_3578459600;
        getBuffer_2805507595.Cycle = cycle_3595310678;
        getBuffer_2805507595.Target = target_2150288829;
        DynamicBufferInput_58384011_id15[IndexX_2446700840] = getBuffer_2805507595;
    }
}
void Compute_id3(inout CS_STREAMS streams)
{

    {
        Compute_id4(streams);
    }
}
void Compute_id2(inout CS_STREAMS streams)
{
    Compute_id3(streams);
}
[numthreads(64, 1, 1)]
void CSMain(CS_INPUT __input__)
{
    CS_STREAMS streams = (CS_STREAMS)0;
    streams.GroupId_id0 = __input__.GroupId_id0;
    streams.DispatchThreadId_id1 = __input__.DispatchThreadId_id1;
    streams.ThreadCountX_id7 = 64;
    streams.ThreadCountY_id8 = 1;
    streams.ThreadCountZ_id9 = 1;
    streams.ThreadCountPerGroup_id5 = 64 * 1 * 1;
    streams.ThreadGroupCount_id4 = ThreadGroupCountGlobal_id10;
    streams.ThreadGroupIndex_id6 = (streams.GroupId_id0.z * streams.ThreadGroupCount_id4.y + streams.GroupId_id0.y) * streams.ThreadGroupCount_id4.x + streams.GroupId_id0.x;
    Compute_id2(streams);
}
